version: "2"
run:
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - cyclop
    - decorder
    - dogsled
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    funlen:
      lines: 80
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
      - ^fp-go/
formatters:
  enable:
    - gofumpt
    - goimports
    - golines
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/dictyBase/fp-go-loom)
    golines:
      max-len: 65
      chain-split-dots: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - ^fp-go/
